### ISSUE TITLE
Jupyter [Errno 110] "Connection timed out"

### ISSUE THREAD

**Issue by tanmay7270** [rohanpooniwala/Nimblebox.ai#5]
#### Issue/Bug description:
Running cells with download requests in Jupyter produces [Errno 110] "Connection timed out" error.

#### Steps to reproduce the issue:
eg: Try downloading resnet50 weights. See screenshot below:

#### Attach screenshot (if applicable):
![41543122_348738005669673_7544537374605180928_n](https://user-images.githubusercontent.com/11278685/45433572-16627380-b6ca-11e8-8b48-a89107183e07.jpg)

**Comment by tanmay7270** [comment]
temporary fix:
>there's a problem in our config, for now, please run this code in a cell:
-@raghavgupta0296 
`import os`
`os.environ['HTTPS_PROXY']="http://10.160.0.2:3128"`
`os.environ['HTTP_PROXY']="http://10.160.0.2:3128"`

**Comment by rohanpooniwala** [comment]
Fixed, works without using the temporary fix.
